services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--username", "$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  orange:
    build:
      dockerfile: cmd/orange/Containerfile
      context: .
    ports:
      - "127.0.0.1:3926:3926"
      - "127.0.0.1:2345:2345"
    environment:
      - ORANGE_LOG_LEVEL=debug
      - ORANGE_SERVERS
      - ORANGE_DISCORD_TOKEN
      - ORANGE_ASR_WORKERS_WHISPER_CF_ACCOUNT_ID
      - ORANGE_ASR_WORKERS_WHISPER_CF_TOKEN
      - ORANGE_ASR_WORKERS_WHISPER_CF_MODEL_NAME
      - ORANGE_POSTGRES_DSN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB?sslmode=disable
    depends_on:
      postgres: 
        condition: service_healthy
volumes:
  postgres-data:
